 platform :ios, '13.0'

target 'MeTA' do
	
  use_modular_headers!

  # Pods for MeTA
	pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'SwiftyJSON'
  pod 'RealmSwift'
  pod 'SquareInAppPaymentsSDK', '1.2.0'

end
