# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'MeTA' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MeTA
	pod 'GoogleMaps'
	pod 'SwiftyJSON'
  pod 'GooglePlaces'

end
